#!/usr/bin/python

# This Python script takes as input a DNA sequence
# The outputs are:
#   1) The position of the first EcoRI restriction site (GAATTC).
#   2) The fragments generated by the cut, and their lengths.

# Preparing the library
import sys

# Getting the DNA sequence
DNA_seq_file = sys.argv[1]

DNA_seq = open(DNA_seq_file).read().rstrip("\n")

# Checking if it is actually a DNA sequence
sorted_seq = sorted(set(DNA_seq))
joined_seq = ''.join(sorted_seq).upper()

if joined_seq == "ACGT":
    print("This looks like a DNA sequence")
else:
    raise ValueError("This is not a DNA sequence!\nIt needs to be only As, Ts, Cs and Gs")

# Finding the first restriction site in the sequence
position = DNA_seq.find("GAATTC")
print("The restriction site starts at position #", position + 1)

# Getting the fragments
first_frag = DNA_seq[0:position + 1]
second_frag = DNA_seq[position + 1:]

len_first_frag = len(first_frag)
len_second_frag = len(second_frag)

print("The fragments generated are:\n\t1st (with ", len_first_frag, "bp):\n\t", first_frag,
        "\n\t2nd (with ", len_second_frag, "bp):\n\t", second_frag)

